% precompute SVD for all datasets
datasets = {...
    'D31';...
    'chainlink';...
    'giant';...
    'ring';...
    'target';...
    'flag';...
    'moon';...
    'lines4';...
    'halfring';...
    'compound';...
    'face320';...
    'spirals3';...
    'pathbased';...
    'rings3';...
    'wave';...
    'hepta';...
    'spiral';...
    'regular';...
    'doughnutDifficultNoise';...
    'doughnutEasyNoise';...
    'breastCancerWisconsin';...
    'fertility';...
    'glass';...
    'ionosphere';...
    'iris';...
    'letterRecognitionABC';...
    'segmentationTrain';...
    'wine';...
    'wineQualityRed3';...
    'yeast';...
    'bladderCarcinoma';...
    'breastCancerWest';...
    'breastColonTumors';...
    'carcinomas';...
    'centralNervousSystem1';...
    'endometrialCancer';...
    'glioblastomaMultiforme';...
    'gliomagenesis';...
    'gliomas1';...
    'hepatocellularCarcinoma';...
    'leukemia1';...
    'leukemia3';...
    'leukemia6';...
    'lungTumor1';...
    'lungTumor2';...
    'lymphoma1';...
    'lymphoma3';...
    'melanoma';...
    'mesothelioma';...
    'multitissue';...
    'prostateCancer2';...
    'prostateCancer3';...
    'prostateCancer5';...
    'roundBluecellTumor';...
    'serratedCarcinomas';...
    'contractions';...
    'laryngeal3';...
    'respiratory';...
    'voice_3';...
    'weaning';...
    };

data_num = length(datasets);
KnnCurr = 1;
saveName = 'precomputedV';

if exist([saveName,'.mat'],'file')
    loadPreV = load(saveName,'Knn');
    Knn = loadPreV.Knn;
    Knn = unique([Knn, KnnCurr]);
    save(saveName,'Knn','datasets','-append');
else
    Knn = KnnCurr;
    save(saveName,'Knn','datasets');
end


V = cell(1,data_num);
T = zeros(data_num,1);
for data_i = 1:data_num
    dataName = datasets{data_i};
    fprintf(1,'%s ... ',dataName);
    % load data and ground-truth labels
    [data,target,info] = pplk_loadData(dataName);
    
    ticID = tic();
    V{data_i} = SPECLS_eigv(data,KnnCurr);
    t = toc(ticID);
    T(data_i) = t;
    V_file = ['V_',dataName,'_knn',num2str(KnnCurr)];
    eval([V_file,'= V{data_i};']);
    save(saveName,V_file, '-append');
    fprintf(1,'%f s\n',t);
end
save(saveName,'T','-append');
save([saveName,'_knn',num2str(KnnCurr),'.mat'],'Knn','datasets','V','T');